### ISSUE TITLE
rm: invalid option -- 'P'

### ISSUE THREAD

**Issue by hafs-r** [bitrise-steplib/steps-secure-delete-path#5]
**secure-delete-path@2.0.0 (exit code: 1)**  
Removing /bitrise/src/app/keystore/release.keystore ...
 (i) NOT using sudo
$ rm -rfP /bitrise/src/app/keystore/release.keystore
rm: invalid option -- 'P'
Try 'rm --help' for more information.

**Comment by fehersanyi-bitrise** [comment]
Hello there!

I made some search, looking around, and there is no `P` flag for the `rm` command 🤔

**Comment by mofobo** [comment]
Hi, I have the same issue:

Removing /bitrise/deploy/*universal* ...
 (i) Using sudo
$ sudo rm -rfP /bitrise/deploy/*universal*
rm: invalid option -- 'P'
Try 'rm --help' for more information.

My workflow run on "Android & Docker, on Ubuntu 16.04"

**Comment by ErYoung2** [comment]
Because rm command thinks something in your item has a ambigious "-p", which doesn't an option in rm command. Just add a path(absolute or relative path) for your file/directory, the bug will be fixed:)

**Comment by itopenup** [comment]
This is the path I've set in the Step's settings:
"/bitrise/deploy/*-bitrise.apk"
Don't understand where is the "-p" here... Except "p" letters inside the path :)

**Comment by sylank** [comment]
The mentioned PR above will fix the issue 😺 .
